### PR TITLE
Update parking lot to 0.11

### PR DESCRIPTION
**Pull request by nico-abram**
Fixes https://github.com/Amanieu/parking_lot/issues/255

### CODE REVIEW

**Comment by nico-abram** [comment]
CI seems to fail for the same reason as https://github.com/Amanieu/seqlock/pull/1#issuecomment-322674372

**Comment by Amanieu** [comment]
Just bump the minimum Rust version in CI to fix the issue.

**Comment by nico-abram** [comment]
Done! I skimmed the readme and didn't see any explicit mention of a MSRV to update

I used 1.31 which I think is the first rust 2018 edition which I think is required for smallvec since it's using `use crate::` (2018 edition mentions use changes [here](https://doc.rust-lang.org/edition-guide/rust-2018/edition-changes.html) and [this](https://travis-ci.org/github/Amanieu/seqlock/jobs/738650922#L234) was the travis run that broke despite having the AtomicUsize method that was previously crashing)

**Comment by nico-abram** [comment]
Oh, it seems smallvec is now breaking on cosnt generics https://travis-ci.org/github/Amanieu/seqlock/jobs/738652796#L240

**Comment by nico-abram** [comment]
I bumped it to 1.36 which seems to be what parking_lot uses in its CI https://github.com/Amanieu/parking_lot/blob/master/.github/workflows/rust.yml#L19

**Comment by Amanieu** [comment]
Thanks!

**Pull request merged**
